#pragma once
#ifndef _YS_MACRO_REC_H_
#define _YS_MACRO_REC_H_

// 宏递归, 最大数量 64
#define YS_EXPAND(...) __VA_ARGS__

#define MACRO_ARG_LIST(header, _64, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53, _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8, _7, _6, _5, _4, _3, _2, _1, N, ...) header##N

// 返回 header##N N为不定参数量,使用loop时 haeder应为MACRO_LOOP_
#define MACRO_ARG_NUM(header, ...) YS_EXPAND(MACRO_ARG_LIST(header, __VA_ARGS__, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1))

// 对不定参中的每一项 执行MACRO_oper(arg)
#define MACRO_LOOP_1(oper, arg1)       oper(arg1)
#define MACRO_LOOP_2(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_1(oper, __VA_ARGS__))
#define MACRO_LOOP_3(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_2(oper, __VA_ARGS__))
#define MACRO_LOOP_4(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_3(oper, __VA_ARGS__))
#define MACRO_LOOP_5(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_4(oper, __VA_ARGS__))
#define MACRO_LOOP_6(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_5(oper, __VA_ARGS__))
#define MACRO_LOOP_7(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_6(oper, __VA_ARGS__))
#define MACRO_LOOP_8(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_7(oper, __VA_ARGS__))
#define MACRO_LOOP_9(oper, arg1, ...)  MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_8(oper, __VA_ARGS__))
#define MACRO_LOOP_10(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_9(oper, __VA_ARGS__))
#define MACRO_LOOP_11(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_10(oper, __VA_ARGS__))
#define MACRO_LOOP_12(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_11(oper, __VA_ARGS__))
#define MACRO_LOOP_13(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_12(oper, __VA_ARGS__))
#define MACRO_LOOP_14(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_13(oper, __VA_ARGS__))
#define MACRO_LOOP_15(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_14(oper, __VA_ARGS__))
#define MACRO_LOOP_16(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_15(oper, __VA_ARGS__))
#define MACRO_LOOP_17(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_16(oper, __VA_ARGS__))
#define MACRO_LOOP_18(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_17(oper, __VA_ARGS__))
#define MACRO_LOOP_19(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_18(oper, __VA_ARGS__))
#define MACRO_LOOP_20(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_19(oper, __VA_ARGS__))
#define MACRO_LOOP_21(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_20(oper, __VA_ARGS__))
#define MACRO_LOOP_22(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_21(oper, __VA_ARGS__))
#define MACRO_LOOP_23(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_22(oper, __VA_ARGS__))
#define MACRO_LOOP_24(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_23(oper, __VA_ARGS__))
#define MACRO_LOOP_25(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_24(oper, __VA_ARGS__))
#define MACRO_LOOP_26(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_25(oper, __VA_ARGS__))
#define MACRO_LOOP_27(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_26(oper, __VA_ARGS__))
#define MACRO_LOOP_28(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_27(oper, __VA_ARGS__))
#define MACRO_LOOP_29(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_28(oper, __VA_ARGS__))
#define MACRO_LOOP_30(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_29(oper, __VA_ARGS__))
#define MACRO_LOOP_31(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_30(oper, __VA_ARGS__))
#define MACRO_LOOP_32(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_31(oper, __VA_ARGS__))
#define MACRO_LOOP_33(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_32(oper, __VA_ARGS__))
#define MACRO_LOOP_34(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_33(oper, __VA_ARGS__))
#define MACRO_LOOP_35(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_34(oper, __VA_ARGS__))
#define MACRO_LOOP_36(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_35(oper, __VA_ARGS__))
#define MACRO_LOOP_37(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_36(oper, __VA_ARGS__))
#define MACRO_LOOP_38(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_37(oper, __VA_ARGS__))
#define MACRO_LOOP_39(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_38(oper, __VA_ARGS__))
#define MACRO_LOOP_40(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_39(oper, __VA_ARGS__))
#define MACRO_LOOP_41(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_40(oper, __VA_ARGS__))
#define MACRO_LOOP_42(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_41(oper, __VA_ARGS__))
#define MACRO_LOOP_43(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_42(oper, __VA_ARGS__))
#define MACRO_LOOP_44(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_43(oper, __VA_ARGS__))
#define MACRO_LOOP_45(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_44(oper, __VA_ARGS__))
#define MACRO_LOOP_46(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_45(oper, __VA_ARGS__))
#define MACRO_LOOP_47(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_46(oper, __VA_ARGS__))
#define MACRO_LOOP_48(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_47(oper, __VA_ARGS__))
#define MACRO_LOOP_49(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_48(oper, __VA_ARGS__))
#define MACRO_LOOP_50(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_49(oper, __VA_ARGS__))
#define MACRO_LOOP_51(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_50(oper, __VA_ARGS__))
#define MACRO_LOOP_52(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_51(oper, __VA_ARGS__))
#define MACRO_LOOP_53(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_52(oper, __VA_ARGS__))
#define MACRO_LOOP_54(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_53(oper, __VA_ARGS__))
#define MACRO_LOOP_55(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_54(oper, __VA_ARGS__))
#define MACRO_LOOP_56(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_55(oper, __VA_ARGS__))
#define MACRO_LOOP_57(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_56(oper, __VA_ARGS__))
#define MACRO_LOOP_58(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_57(oper, __VA_ARGS__))
#define MACRO_LOOP_59(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_58(oper, __VA_ARGS__))
#define MACRO_LOOP_60(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_59(oper, __VA_ARGS__))
#define MACRO_LOOP_61(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_60(oper, __VA_ARGS__))
#define MACRO_LOOP_62(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_61(oper, __VA_ARGS__))
#define MACRO_LOOP_63(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_62(oper, __VA_ARGS__))
#define MACRO_LOOP_64(oper, arg1, ...) MACRO_LOOP_1(oper, arg1) YS_EXPAND(MACRO_LOOP_63(oper, __VA_ARGS__))

#endif